Repository SOPT-all/35-APPJAM-ANDROID-GONGBAEK, pull requests merged in 2025-01, with the labels that each got.

#4 [Add/#3] Color System 및 Typography를 추가합니다.
  .editorconfig
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/gongbaek/ui/theme/Color.kt
  app/src/main/java/com/sopt/gongbaek/ui/theme/Theme.kt
  app/src/main/java/com/sopt/gongbaek/ui/theme/Type.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: ✨ Feat, ➕ Add, 🐶 대현

#6 [Init/#5] 네비게이션 기초세팅을 진행합니다.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/navigation/GroupDetailNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/navigation/GroupDetailNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/navigation/GroupListNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/navigation/GroupListNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/navigation/GroupRegisterNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/navigation/GroupRegisterNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCategoryScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCoverScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCycleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupPlacePeopleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/SelectDayOfWeekScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/SelectDayScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/navigation/HomeNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/navigation/MyGroupNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/navigation/MyGroupNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/navigation/OnboardingNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/navigation/OnboardingNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/CompleteOnboardingScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/EnterTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/GapTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/GenderScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/GradeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/MajorSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/SelectProfileScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/SelfIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/UnivMajorScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/UnivSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/splash/SplashScreen.kt
Labels: ⚙ Init, 🌱 민재

#8 [Feat/#7] 하단 탭바를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/model/NavigationRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/MainBottomNavBarTabType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/ExampleComponent.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/navigation/GroupDetailNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/navigation/GroupDetailNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/navigation/GroupListNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/navigation/GroupListNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/navigation/GroupRegisterNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/navigation/GroupRegisterNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/navigation/GroupRoomNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/navigation/GroupRoomNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/navigation/HomeNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainBottomNavBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/navigation/MyGroupNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/navigation/MyGroupNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/navigation/OnboardingNavGraph.kt
  app/src/main/res/drawable/ic_android_black_24dp.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#10 [Feat/#9] 이미지 버튼 공통 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/type/ImageSelectorType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/ImageSelector.kt
  app/src/main/res/drawable/ic_check_fill_24.xml
  app/src/main/res/drawable/img_image_button_sample.png
Labels: ✨ Feat, ❤️‍🔥 민서

#15 [Feat/#12] 기본 버튼 공통 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/GongBaekBasicButton.kt
Labels: ✨ Feat, 🐶 대현

#17 [Feat/#14] 탑바 공통 컴포넌트 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/topbar/CenterTitleTopBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/topbar/StartTitleTopBar.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#20 [Feat/#13] textField 공통 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/type/GongBaekBasicTextFieldType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/textfield/GongBaekBasicTextField.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🐶 대현

#22 [Feat/#21] ProgressBar 공통 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/progressBar/GongBaekProgressBar.kt
Labels: ✨ Feat, 🐶 대현

#27 [Feat/#18] 모임 정보 칩 공통 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/type/GroupInfoChipType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/chip/GroupInfoChip.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#29 [Feat/#28] 다이얼로그 공통 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/type/GongBaekDialogType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/GongBaekBasicButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/chip/GroupInfoChip.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/dialog/GongBaekDialog.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#31 [Feat/#25] 선택 가능한 버튼 공통 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/domain/type/DayOfWeekType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/GenderType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/GradeType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/GroupCycleType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/MbtiFirstLetterType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/MbtiFourthLetterType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/MbtiSecondLetterType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/MbtiThirdLetterType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/SelectableButtonType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/GongBaekSelectableButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/textfield/GongBaekBasicTextField.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/extension/MbtiCreator.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#32 [Feat/#30] "모임 등록 > 장소,인원 선택 뷰" 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/PageDescriptionSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/component/GroupPeopleCounter.kt
  app/src/main/res/drawable/ic_minus_main_orange_18.xml
  app/src/main/res/drawable/ic_plus_main_orange_18.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#36 [Feat/#34] 모임 정보 컨테이너 공통 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/chip/GroupInfoChip.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupPeopleDescription.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupPlaceDescription.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupTimeDescription.kt
Labels: ✨ Feat, 🌱 민재

#40 [Feat/#37] "모임방 뷰" UI를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/domain/model/Comment.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupComment.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupInfo.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupPeople.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/GroupCategoryType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/GroupCycleType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/GroupStatusType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/GroupInfoChipType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/CommentSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/extension/GroupTimeDescriptionCreator.kt
  app/src/main/res/drawable/ic_people_18.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#45 [Chore/#44] 확정된 바텀 네비게이션 UI를 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/type/MainBottomNavBarTabType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainBottomNavBar.kt
Labels: ❤️‍🩹 Chore, 🌱 민재

#39 [Feat/#35] "모임 등록 > 날짜 선택 뷰" 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/component/SelectDayCalendar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/extension/CalendarCalculator.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#49 [Feat/#24] timetable 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/GongBaekTimeTable.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/GroupRegisterTimeTable.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/LectureTimeSelectionTable.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/item/DayHeaderItem.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/item/TimeLabelsItem.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/timetable/GenerateTimeLabels.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/timetable/GroupConsecutiveIndices.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/timetable/StartAndExpandSelection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/timetable/UpdateSelectedTimeSlots.kt
Labels: ✨ Feat, 🐶 대현

#51 [Feat/#48] "나의채움 뷰" UI를 구현합니다.
  .github/workflows/main.yml
  app/build.gradle.kts
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupInfo.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/MyGroupPagerType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/tabpager/CustomTabPager.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyApplyScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreenContent.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyRegisterScreen.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#53 [Feat/#41] "채우기 뷰" UI를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/domain/type/DayOfWeekType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/GroupCategoryType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/component/CategoryBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/component/CycleBottomSheetPresenter.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/component/DayOfWeekBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/component/GongBaekToggleButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/component/SelectDayCalendar.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#55 [Feat/#52] "모임 상세 뷰" UI를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupHost.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/CategoryType.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/GenderType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/GroupDetailPagerType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/SelectableButtonType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/CommentSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/tabpager/CustomTabPager.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailCommentScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailInfoScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/FormatEnterYear.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#57 [Feat/#50] "회원가입 > 1. 프로필 선택, 2. 닉네임 입력" UI를 구현합니다.
  app/build.gradle.kts
  app/src/main/java/com/sopt/gongbaek/domain/model/TimeTable.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/UserInfo.kt
  app/src/main/java/com/sopt/gongbaek/presentation/model/NavigationRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/ImageSelectorType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EnterTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GapTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GenderScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GradeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MajorSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelectProfileScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelfIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/UnivMajorScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/UnivSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/ImageSelector.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/navigation/OnboardingNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/navigation/OnboardingNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/MajorSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/SelectProfileScreen.kt
  app/src/main/res/drawable/img_profile_0_104.png
  app/src/main/res/drawable/img_profile_1_104.png
  app/src/main/res/drawable/img_profile_2_104.png
  app/src/main/res/drawable/img_profile_3_104.png
  app/src/main/res/drawable/img_profile_4_104.png
  app/src/main/res/drawable/img_profile_5_104.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ Feat, 🐶 대현

#59 [Feat/#56] 스플래시 화면과 온보딩 화면을 구현합니다.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_gongbaek_launcher-playstore.png
  app/src/main/java/com/sopt/gongbaek/presentation/model/NavigationRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/navigation/OnboardingNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen1.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen2.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen3.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/splash/SplashScreen.kt
  app/src/main/res/drawable/ic_gongbaek_launcher_background.xml
  app/src/main/res/drawable/img_onboard_illustration1.png
  app/src/main/res/drawable/img_onboard_illustration2.png
  app/src/main/res/drawable/img_onboard_illustration3.png
  app/src/main/res/mipmap-anydpi-v26/ic_gongbaek_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_gongbaek_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_gongbaek_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_gongbaek_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_gongbaek_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_gongbaek_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_gongbaek_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_gongbaek_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_gongbaek_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_gongbaek_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_gongbaek_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_gongbaek_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_gongbaek_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_gongbaek_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_gongbaek_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_gongbaek_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_gongbaek_launcher_round.webp
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ Feat, 🌱 민재

#61 [Feat/#58] "회원가입 UI" 를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/model/NavigationRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/component/SearchButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/ChangeTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/CompleteAuthScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EnterTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GapTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GenderScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GradeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelectProfileScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelfIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/UnivMajorScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/PageDescriptionSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/GongBaekTimeTable.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/GroupRegisterTimeTable.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/LectureTimeSelectionTable.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🐶 대현

#63 [Feat/#54] "등록하기 뷰" UI를 구현합니다.
  app/build.gradle.kts
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupRegisterInfo.kt
  app/src/main/java/com/sopt/gongbaek/presentation/model/NavigationRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/SelectableButtonType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/ImageSelector.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/PageDescriptionSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/GroupRegisterTimeTable.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/navigation/GroupListNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/component/GroupCategorySelectableButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/component/GroupPeopleCounter.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/component/SelectDayCalendar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/navigation/GroupRegisterNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/navigation/GroupRegisterNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCategoryScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCoverScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCycleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupPlacePeopleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/SelectDayOfWeekScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/SelectDayScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/GroupRegisterTimeDescriptionCreator.kt
  app/src/main/res/drawable/img_category_dining.png
  app/src/main/res/drawable/img_category_exercise.png
  app/src/main/res/drawable/img_category_networking.png
  app/src/main/res/drawable/img_category_others.png
  app/src/main/res/drawable/img_category_playing.png
  app/src/main/res/drawable/img_category_study.png
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#69 [Feat/#67] 스플래시 화면에 Lottie를 적용합니다.
  app/build.gradle.kts
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/GongBaekLottieAnimation.kt
  app/src/main/res/raw/lottie_splash.json
  gradle/libs.versions.toml
Labels: ✨ Feat, 🌱 민재

#70 [Feat/#62] Home 화면 ui를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/HomeBannerSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/MemberRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/NearestGroupSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/OnceRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/WeekRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/res/drawable/img_detail_profile_0.png
  app/src/main/res/drawable/img_detail_profile_1.png
  app/src/main/res/drawable/img_detail_profile_2.png
  app/src/main/res/drawable/img_detail_profile_3.png
  app/src/main/res/drawable/img_detail_profile_4.png
  app/src/main/res/drawable/img_detail_profile_5.png
  app/src/main/res/drawable/img_home_banner.png
  app/src/main/res/drawable/img_home_main.png
  app/src/main/res/drawable/img_home_profile_small_0.png
  app/src/main/res/drawable/img_home_profile_small_1.png
  app/src/main/res/drawable/img_home_profile_small_2.png
  app/src/main/res/drawable/img_home_profile_small_3.png
  app/src/main/res/drawable/img_home_profile_small_4.png
  app/src/main/res/drawable/img_home_profile_small_5.png
  app/src/main/res/drawable/img_home_recommend_0.png
  app/src/main/res/drawable/img_home_recommend_1.png
  app/src/main/res/drawable/img_home_recommend_2.png
  app/src/main/res/drawable/img_home_recommend_3.png
  app/src/main/res/drawable/img_home_recommend_4.png
  app/src/main/res/drawable/img_home_recommend_5.png
Labels: ✨ Feat, 🐶 대현

#71 [Chore/#65] 스플래시 화면 상단 뒤로가기 버튼을 수정합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen1.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen2.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen3.kt
Labels: ❤️‍🩹 Chore, 🌱 민재

#75 [Feat/#74] 전체 다이얼로그 공통 컴포넌트를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/type/GongBaekDialogType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/dialog/GongBaekDialog.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
  app/src/main/res/drawable/img_dialog_fail.png
  app/src/main/res/drawable/img_dialog_success.png
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#77 [Feat/#60] "모임방 뷰" 로직을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupComment.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupComments.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupHost.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupInfo.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupPeople.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/TimeTable.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/UserInfo.kt
  app/src/main/java/com/sopt/gongbaek/presentation/model/NavigationRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelectProfileScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/CommentSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailCommentScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/navigation/GroupRoomNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/navigation/GroupRoomNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreenContent.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/FormatGroupTimeDescription.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/GroupRegisterTimeDescriptionCreator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/base/UiLoadState.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#78 [Feat/#73] "나의모임 뷰" 로직을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyApplyScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreenContent.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyRegisterScreen.kt
  app/src/main/res/drawable/img_fire_18.png
  app/src/main/res/drawable/img_lock_18.png
  app/src/main/res/drawable/img_my_fill_active_empty.png
  app/src/main/res/drawable/img_my_fill_closed_empty.png
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#82 [Refactor/#80] 시간표 로직을 수정합니다.
  app/src/main/java/com/sopt/gongbaek/domain/type/DayOfWeekType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/GongBaekTimeTable.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/GroupRegisterTimeTable.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/LectureTimeSelectionTable.kt
Labels: ♻️ Refactor, 🐶 대현

#84 [Feat/#79] "모임상세 뷰" 로직을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupInfo.kt
  app/src/main/java/com/sopt/gongbaek/presentation/model/NavigationRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/CommentSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/navigation/GroupDetailNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/navigation/GroupDetailNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailCommentScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/FormatGroupTimeDescription.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#86 [Feat/#64] "등록하기 뷰" 로직을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupRegisterInfo.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/DayOfWeekType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/SelectableButtonType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GenderScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GradeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/GongBaekSelectableButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/dialog/GongBaekDialog.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/component/GroupPeopleCounter.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/navigation/GroupRegisterNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCategoryScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCoverScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCycleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupPlacePeopleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/SelectDayOfWeekScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/SelectDayScreen.kt
Labels: ✨ Feat, ❤️‍🔥 민서

#91 [Feat/#85] "나의모임 뷰" API를 연결합니다.
  app/src/main/java/com/sopt/gongbaek/data/local/datasource/TokenLocalDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/local/datasourceimpl/TokenLocalDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/MyGroupsResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/GroupRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/GroupRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/request/MyGroupsRequestDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/BaseGroupInfoResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/MyGroupsResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/GroupService.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/util/AuthInterceptor.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/GroupRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/TokenRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/di/DataSourceModule.kt
  app/src/main/java/com/sopt/gongbaek/di/NetworkModule.kt
  app/src/main/java/com/sopt/gongbaek/di/RepositoryModule.kt
  app/src/main/java/com/sopt/gongbaek/di/ServiceModule.kt
  app/src/main/java/com/sopt/gongbaek/di/SharedPreferencesModule.kt
  app/src/main/java/com/sopt/gongbaek/di/UseCaseModule.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupInfo.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/GroupRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/TokenRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/GetMyGroupsUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupViewModel.kt
Labels: ✨ Feat, 🌱 민재

#93 [Feat/#88] "채우기 뷰" 로직을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/component/GongBaekToggleButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/navigation/GroupListNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreenContent.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#94 [Feat/#89] "채우기 뷰" API를 연결합니다.
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/GroupListGroupResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/GroupRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/GroupRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/GroupListGroupResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/GroupService.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/GroupRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/di/UseCaseModule.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/GroupRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/GetGroupsUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
Labels: ✨ Feat, ❤️‍🔥 민서

#95 [Feat/#87] "회원가입 뷰" API를 연결합니다.
  app/src/main/java/com/sopt/gongbaek/data/mapper/todata/TimeTableMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todata/UserInfoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/RegisterUserInfoResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/SearchMajorsResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/SearchUniversitiesResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/SearchRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/AuthRemoteDatasourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/SearchRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/base/NullableApiResponse.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/request/RegisterTimeTableRequestDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/request/RegisterUserInfoRequestDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/RegisterUserInfoResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/SearchMajorsResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/SearchUniversitiesResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/AuthService.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/SearchService.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/util/ApiResponseException.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/util/ApiResponseHandler.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/SearchRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/di/DataSourceModule.kt
  app/src/main/java/com/sopt/gongbaek/di/RepositoryModule.kt
  app/src/main/java/com/sopt/gongbaek/di/ServiceModule.kt
  app/src/main/java/com/sopt/gongbaek/di/UseCaseModule.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/UserAuth.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/SearchRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/GetSearchMajorsResultUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/GetSearchUniversitiesResultUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/RegisterUserInfoUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/SetTokenUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/ValidateNicknameUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GapTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/extension/CharExt.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/timetable/ConvertToTimeTable.kt
Labels: ✨ Feat, 🐶 대현

#98 [Feat/#83] "홈 화면" 로직을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/domain/model/NearestGroup.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/RecommendGroupInfo.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/MemberRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/NearestGroupSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/OnceRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/WeekRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/timetable/NearestGroupFormatSchedule.kt
  app/src/main/res/drawable/img_detail_profile_0.png
  app/src/main/res/drawable/img_detail_profile_1.png
  app/src/main/res/drawable/img_detail_profile_2.png
  app/src/main/res/drawable/img_detail_profile_3.png
  app/src/main/res/drawable/img_detail_profile_4.png
  app/src/main/res/drawable/img_detail_profile_5.png
  app/src/main/res/drawable/img_detail_profile_6.png
  app/src/main/res/drawable/img_home_profile_small_0.png
  app/src/main/res/drawable/img_home_profile_small_1.png
  app/src/main/res/drawable/img_home_profile_small_2.png
  app/src/main/res/drawable/img_home_profile_small_3.png
  app/src/main/res/drawable/img_home_profile_small_4.png
  app/src/main/res/drawable/img_home_profile_small_5.png
  app/src/main/res/drawable/img_home_profile_small_6.png
  app/src/main/res/drawable/img_home_recommend_0.png
  app/src/main/res/drawable/img_home_recommend_1.png
  app/src/main/res/drawable/img_home_recommend_2.png
  app/src/main/res/drawable/img_home_recommend_3.png
  app/src/main/res/drawable/img_home_recommend_4.png
  app/src/main/res/drawable/img_home_recommend_5.png
  app/src/main/res/drawable/img_home_recommend_6.png
Labels: ✨ Feat, 🐶 대현

#96 [Feat/#90] "등록하기 뷰" API를 연결합니다.
  app/src/main/java/com/sopt/gongbaek/data/mapper/todata/GroupRegisterRequestDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/GroupRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/GroupRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/request/GroupRegisterRequestDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/GroupRegisterResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/GroupService.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/GroupRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/di/UseCaseModule.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/GroupRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/PostGroupUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavigator.kt
Labels: ✨ Feat, ❤️‍🔥 민서

#97 [Feat/#92] "모임상세 뷰" API를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/data/mapper/todata/CommentMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/GroupCommentsResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/GroupDetailResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/GroupHostResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/PostCommentResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/CommentRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/GroupRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/CommentRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/GroupRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/request/PostCommentRequestDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/GroupCommentsResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/GroupDetailResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/GroupHostResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/PostCommentResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/CommentService.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/GroupService.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/CommentRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/GroupRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/di/DataSourceModule.kt
  app/src/main/java/com/sopt/gongbaek/di/RepositoryModule.kt
  app/src/main/java/com/sopt/gongbaek/di/ServiceModule.kt
  app/src/main/java/com/sopt/gongbaek/di/UseCaseModule.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/Comment.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupDetail.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/CommentRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/GroupRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/ApplyGroupUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/GetGroupCommentsUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/LoadGroupDetailScreenUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/PostCommentUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/ImageSelectorType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/navigation/MyGroupNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreenContent.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/FormatGroupTimeDescription.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/timetable/NearestGroupFormatSchedule.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#103 [Fix/#101] 자체 QA를 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelfIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/component/DayOfWeekBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCoverScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupPlacePeopleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
  app/src/main/res/values/strings.xml
Labels: 🛠️ Fix, ❤️‍🔥 민서

#102 [Feat/#100] "모임방 뷰" API를 연결합니다.
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/GroupMembersResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/GroupRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/GroupRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/request/ApplyGroupRequestDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/GroupMembersResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/GroupService.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/GroupRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/di/UseCaseModule.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupMembers.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupRoom.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/GroupRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/LoadGroupRoomScreenUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/model/ProfileImageList.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/navigation/GroupDetailNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/navigation/GroupRoomNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/FormatGroupTimeDescription.kt
Labels: ✨ Feat, 🌱 민재

#109 [Fix/105] 시간표 로직을 수정합니다.
  app/src/main/java/com/sopt/gongbaek/data/local/datasourceimpl/TokenLocalDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterViewModel.kt
Labels: 🛠️ Fix, ❤️‍🔥 민서

#111 [Fix/#108] "홈 화면" UI를 개선합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCoverScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/OnceRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/WeekRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/NearestGroupFormatSchedule.kt
Labels: ✨ Feat, 🐶 대현

#113 [Refactor/#112] "홈 화면" 1차 QA 사항을 반영합니다.
  app/src/main/java/com/sopt/gongbaek/domain/type/DayOfWeekType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/WeekRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/FormatGroupTimeDescription.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/GroupRegisterTimeDescriptionCreator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/NearestGroupFormatSchedule.kt
Labels: 🛠️ Fix, ♻️ Refactor, 🐶 대현

#116 [Refactor/#114] "회원가입 화면" 1차 QA 사항을 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/CompleteAuthScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/NicknameScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelfIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/textfield/GongBaekBasicTextField.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/extension/CharExt.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/extension/StringExt.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ♻️ Refactor, 🐶 대현

#118 [Refactor/#110] 1차 QA 수정사항을 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EnterTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/GapTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/navigation/GroupRoomNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreenContent.kt
Labels: ♻️ Refactor, 🌱 민재

#117 [Chore/#115] "채우기 화면", "다이얼로그 공통 컴포넌트" 1차 QA 사항을 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/dialog/GongBaekDialog.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/component/CategoryBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/component/GongBaekToggleButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupPlacePeopleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ❤️‍🩹 Chore, ❤️‍🔥 민서

#119 [Hotfix/120] 등록 오류 해결
  app/src/main/java/com/sopt/gongbaek/data/local/datasourceimpl/TokenLocalDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MajorSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/UnivSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavigator.kt
Labels: 🚨 Hotfix, ❤️‍🔥 민서
